#+STARTUP: content indent

- Ubuntu 18.04 で タッチパッド の感度を調整するための設定

* 参考情報
- [[https://help.ubuntu.com/community/SynapticsTouchpad][SynapticsTouchpad@Ubuntu Documentation]]
- [[https://askubuntu.com/questions/483707/14-04-touchpad-is-too-sensitive][14.04 Touchpad is too sensitive@StackExchange]]

* Synaptics Driver のインストール

- Synaptics はタッチパッドなどのドライバのこと
#+begin_src shell
sudo apt-get install xserver-xorg-input-synaptics
#+end_src

* 設定確認のためのコマンド

#+begin_src shell
xinput list

xinput list-props "SynPS/2 Synaptics TouchPad"
# or
xinput list-props 11 # (デバイス番号で指定)
#+end_src

* 設定方法 
** コマンド

- Synaptics Finger の引数の意味
  - Low, High 2 づつ増やして試す
#+begin_src shell
xinput --set-prop 11 "Synaptics Finger" 47, 52, 0
xinput --set-prop 11 "Synaptics Noise Cancellation" 20 20
#+end_src

** Synaptics Finger の設定の意味
- https://www.x.org/archive/X11R7.5/doc/man/man4/synaptics.4.html

- Option "FingerLow" "integer"
  When finger pressure drops below this value, the driver counts it as a release. Property: "Synaptics Finger"

- Option "FingerHigh" "integer"
   When finger pressure goes above this value, the driver counts it as a touch. Property: "Synaptics Finger"

- Option "FingerPress" "integer"
   When finger pressure goes above this value, the driver counts it as a press. Currently a press is equivalent to putting the touchpad in trackstick emulation mode. Property: "Synaptics Finger"

** 設定の永続化

- 最適な設定値が見つかったら、以下に記載していおく
  - =/usr/share/X11/xorg.conf.d/70-synaptics.conf=

#+begin_quote
Section "InputClass"
        Identifier "touchpad catchal
        Driver "synaptics"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        option "FingerLow" "32"
        Option "FingerHigh" "35"
EndSectio
#+end_quote
