#+STARTUP:  content indent

* emacs 26 package

- Flycheck support start from emacs 26 (and require lintr for R)
  - だたし、R で Flycheck が有効になると、sentinel error 多発で、重くなる

#+begin_src shell
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt update
sudo apt install emacs26
#+end_src

- すでに emacs25 がある環境では、以下を実行して削除
#+begin_src shell
sudo apt remove --purge emacs25-nox
sudo apt remove --purge emacs25-el
sudo apt remove --purge emacs25-common
sudo apt remove --purge emacs25
#+end_src

* build from source
** 手順

- [[https://www.reddit.com/r/emacs/comments/eu7s5e/how_to_update_to_emacs_27/][How to update to emacs 27?]]

#+begin_src shell :eval never
git clone https://github.com/emacs-mirror/emacs.git

# すべての履歴が必要ない場合は、depth 1 でOK
# git clone --depth 1 git::/git.savannah.gnu.org/emacs.git

cd emacs
git checkout emacs-27

./autogen.sh

# emacs 27
./configure --prefix=$HOME/emacs/emacs-27.0.91 --with-mailutils --with-cairo --with-xwidgets --with-imagemagick --without-xaw3d

# emacs 26
./configure --prefix=$HOME/emacs/emacs-26.3 --with-mailutils --with-cairo --with-xwidgets --with-modules --without-xaw3d

make

./src/emacs --version
make install
#+end_src

** configure options

- Should Emacs use a relocating allocator for buffers?
  - [[https://stackoverflow.com/questions/26192944/what-is-relocating-allocator-for-buffers-in-emacs][What is relocating allocator for buffers in Emacs?@Stackoverflow]]
  - no のままで良さそう

- Should Emacs use mmap(2) for buffer allocation?
  - [[https://stackoverflow.com/questions/6328002/emacs-buffer-allocation-using-mmap][Emacs Buffer Allocation using mmap@Stackoverflow]]

- 必要なオプションが有効になっていない場合は、依存関係をインストールする
  - jansson (JSON) - =libjansson-dev=
  - rsvg - =librsvg2-dev=
  - cairo (絵文字などの画像表示) - =libcairo2-dev= & =--with-cairo=
  - Xaw3d (X Athena Widgets) - 依存関係が不明のため =--without-xaw3d=
  - Xwidgets - =libwebkit2gtk-4.0-dev= & =--with-xwidgets=
  - lcms2 (Little CMS) - =liblcms2-dev=
  - imagemagick - =libmagickwand-dev= & =--with-imagemagick=
  - gpm (Console Mouse Support) - =libgpm-dev=
  - gconf - Gsetting が有効なため不要
  - access control list - =libacl1-dev=
  - selinux - =libselinux1-dev=
  - otf - =libotf-dev=
  - xtf - =libxft-dev=
  - m17n-flt - =libm17n-dev=
  - systemd - =libsystemd-dev=

- X Toolkit は特に指定しなければ =--with-x-toolkit=gtk3=
#+begin_quote
Where should the build process find the source code?    .
What compiler should emacs be built with?               gcc -g3 -O2
Should Emacs use the GNU version of malloc?             no
  (The GNU allocators don't work with this system configuration.)
Should Emacs use a relocating allocator for buffers?    no
Should Emacs use mmap(2) for buffer allocation?         no
What window system should Emacs use?                    x11
What toolkit should Emacs use?                          GTK3
Where do we find X Windows header files?                Standard dirs
Where do we find X Windows libraries?                   Standard dirs
Does Emacs use -lXaw3d?                                 no
Does Emacs use -lXpm?                                   yes
Does Emacs use -ljpeg?                                  yes
Does Emacs use -ltiff?                                  yes
Does Emacs use a gif library?                           yes -lgif
Does Emacs use a png library?                           yes -lpng16 -lz
Does Emacs use -lrsvg-2?                                yes
Does Emacs use cairo?                                   yes
Does Emacs use -llcms2?                                 yes
Does Emacs use imagemagick?                             yes
Does Emacs support sound?                               yes
Does Emacs use -lgpm?                                   yes
Does Emacs use -ldbus?                                  yes
Does Emacs use -lgconf?                                 no
Does Emacs use GSettings?                               yes
Does Emacs use a file notification library?             yes -lglibc (inotify)
Does Emacs use access control lists?                    yes -lacl
Does Emacs use -lselinux?                               yes
Does Emacs use -lgnutls?                                yes
Does Emacs use -lxml2?                                  yes
Does Emacs use -lfreetype?                              yes
Does Emacs use HarfBuzz?                                yes
Does Emacs use -lm17n-flt?                              yes
Does Emacs use -lotf?                                   yes
Does Emacs use -lxft?                                   no
Does Emacs use -lsystemd?                               yes
Does Emacs use -ljansson?                               yes
Does Emacs use -lgmp?                                   yes
Does Emacs directly use zlib?                           yes
Does Emacs have dynamic modules support?                yes
Does Emacs use toolkit scroll bars?                     yes
Does Emacs support Xwidgets (requires gtk3)?            yes
Does Emacs have threading support in lisp?              yes
Does Emacs support the portable dumper?                 yes
Does Emacs support legacy unexec dumping?               no
Which dumping strategy does Emacs use?                  pdumper
#+end_quote

** GTK+ error

- [[https://tamurashingo.github.io/post/2019/03/19/emacs-install-succeeded/][Emacs 26.1のインストール(成功編)]]

- GTK+3 を入れたことによるエラーの模様
#+begin_quote
configure: WARNING: Your version of Gtk+ will have problems with
       closing open displays.  This is no problem if you just use
       one display, but if you use more than one and close one of them
       Emacs may crash.
       See https://bugzilla.gnome.org/show_bug.cgi?id=85715
#+end_quote

** system-configuration-options

#+begin_src emacs-lisp
emacs-version
#+end_src

#+RESULTS:
: 26.3

#+begin_src emacs-lisp
system-configuration-options
#+end_src

#+RESULTS:
: --with-mailutils --with-cairo --with-xwidgets --with-modules --without-xaw3d

* Windows
** 日本語パッチ -> *Official を使った方が実際はトラブルが少かった*

- [[https://github.com/chuntaro/NTEmacs64][Windows 版 Emacs (通称 NTEmacs) の 64bit 版]]
- [[http://cha.la.coocan.jp/doc/NTEmacs.html][NTEmacs / Emacs for Windows]]

** 環境変数

- .emacs.d\ created at C:\Users\hoge\AppData\Roaming\
- 環境変数に C:\User\shun を設定（これをしないと AppData\Roaming が HOME のまま）

* spacemacs
** clone

#+begin_src shell
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

cd ~/.emacs.d
git checkout develop
#+end_src

** spacemacs を最新に更新

- [[https://qiita.com/osamu2001/items/43ca7977b2667daef2a9][Spacemacsを最新状態にしたい@Qiita]]
#+begin_src shell
cd ~/src/github.com/syl20bnr/spacemacs
git fetch --prune
git checkout --force develop
git reset --hard origin/develop
emacsclient -e '(configuration-layer/update-packages t)'
emacsclient -e '(dotspacemacs/sync-configuration-layers)'
emacsclient -e '(spacemacs/restart-emacs-resume-layouts)'
#+end_src

** Windows 10

- [[http://cpthgli.hatenablog.jp/entry/2016/12/21/Windows10%E3%81%A7Spacemacs%21%21][Windows10でSpacemacs!!]]

* emacs options

- [[http://www.itsenka.com/contents/development/unix-linux/emacs.html][emacs - UNIX/Linuxコマンド - IT専科]] 

- =--batch=       バッチモード (elisp プログラムを実行するため)
- =--debug-init=  起動時にデバッガを有効にする
- =-q=            個人用設定ファイルを読み込まない
- =-nw=           GUI なし
- =-l hoge.el=    指定したファイルを読み込む。バッチモードと組み合わせる。
- =-f func=       指定した関数を実行

* package

- [[https://emacs.stackexchange.com/questions/44266/require-vs-package-initialize#:~:text=package%2Dinitialize%20goes%20through%20the,ve%20previously%20installed%20will%20work.][init file - require vs. package-initialize? - Emacs Stack Exchange]] 

- =(pacakge-initialize)=
  - インストール済みのパッケージの =autoloads= を読み込む
  - なので、autoload 指定された関数であれば =(require 'hoge)= しなくても利用可能になる

* TODO GC cons threshold
* TODO Portable Dumper

- [[https://archive.casouri.cat/note/2020/painless-transition-to-portable-dumper/index.html][Painless Transition to Portable Dumper]]

- 基本的な流れ
#+begin_src shell

# dump file 作成
# (dump-emacs-portable) 関数はバッチモードでのみ有効
emacs --batch -q -l ~/.emacs.d/dump.el

# dump を使って起動
emacs --dump-file="/home/shun/.emacs.d/emacs.pdmp"
#+end_src  

- その他
  - [[http://emacs.rubikitch.com/esup/][esup.el : Emacs起動が遅い原因を探れ！init-loader.el対応コードあり]]
  - [[https://futurismo.biz/archives/2849][Emacs 高速化起動にむけたカイゼンのとりくみ | Futurismo]] 

- Segfault 
  - [[https://github.com/syl20bnr/spacemacs/issues/10770][syl20bnr/spacemacs#10770 Loading Portable dumper file causing segmentation falut]]
